package com.zhang.automobile_management_system.mapper;

import com.zhang.automobile_management_system.bean.AfterSale;
import com.zhang.automobile_management_system.bean.AfterSaleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AfterSaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int countByExample(AfterSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int deleteByExample(AfterSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int deleteByPrimaryKey(Integer afterSaleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int insert(AfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int insertSelective(AfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    List<AfterSale> selectByExample(AfterSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    AfterSale selectByPrimaryKey(Integer afterSaleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int updateByExampleSelective(@Param("record") AfterSale record, @Param("example") AfterSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int updateByExample(@Param("record") AfterSale record, @Param("example") AfterSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int updateByPrimaryKeySelective(AfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    int updateByPrimaryKey(AfterSale record);
}