package com.zhang.automobile_management_system.mapper;

import com.zhang.automobile_management_system.bean.Announcement;
import com.zhang.automobile_management_system.bean.AnnouncementExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int countByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int deleteByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int deleteByPrimaryKey(Integer announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int insert(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int insertSelective(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    List<Announcement> selectByExample(AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    Announcement selectByPrimaryKey(Integer announcementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int updateByExampleSelective(@Param("record") Announcement record, @Param("example") AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int updateByExample(@Param("record") Announcement record, @Param("example") AnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int updateByPrimaryKeySelective(Announcement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    int updateByPrimaryKey(Announcement record);
}