package com.zhang.automobile_management_system.mapper;

import com.zhang.automobile_management_system.bean.CarMessagesSale;
import com.zhang.automobile_management_system.bean.CarMessagesSaleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CarMessagesSaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int countByExample(CarMessagesSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int deleteByExample(CarMessagesSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int deleteByPrimaryKey(String carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int insert(CarMessagesSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int insertSelective(CarMessagesSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    List<CarMessagesSale> selectByExample(CarMessagesSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    CarMessagesSale selectByPrimaryKey(String carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int updateByExampleSelective(@Param("record") CarMessagesSale record, @Param("example") CarMessagesSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int updateByExample(@Param("record") CarMessagesSale record, @Param("example") CarMessagesSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int updateByPrimaryKeySelective(CarMessagesSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_messages_sale
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    int updateByPrimaryKey(CarMessagesSale record);
}