package com.zhang.automobile_management_system.mapper;

import com.zhang.automobile_management_system.bean.CarOrder;
import com.zhang.automobile_management_system.bean.CarOrderExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CarOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int countByExample(CarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int deleteByExample(CarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int insert(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int insertSelective(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    List<CarOrder> selectByExample(CarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    CarOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int updateByExampleSelective(@Param("record") CarOrder record, @Param("example") CarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int updateByExample(@Param("record") CarOrder record, @Param("example") CarOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int updateByPrimaryKeySelective(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    int updateByPrimaryKey(CarOrder record);
}