package com.zhang.automobile_management_system.bean;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
@Component
public class AfterSaleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public AfterSaleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAfterSaleIdIsNull() {
            addCriterion("after_sale_id is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdIsNotNull() {
            addCriterion("after_sale_id is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdEqualTo(Integer value) {
            addCriterion("after_sale_id =", value, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdNotEqualTo(Integer value) {
            addCriterion("after_sale_id <>", value, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdGreaterThan(Integer value) {
            addCriterion("after_sale_id >", value, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("after_sale_id >=", value, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdLessThan(Integer value) {
            addCriterion("after_sale_id <", value, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdLessThanOrEqualTo(Integer value) {
            addCriterion("after_sale_id <=", value, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdIn(List<Integer> values) {
            addCriterion("after_sale_id in", values, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdNotIn(List<Integer> values) {
            addCriterion("after_sale_id not in", values, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdBetween(Integer value1, Integer value2) {
            addCriterion("after_sale_id between", value1, value2, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("after_sale_id not between", value1, value2, "afterSaleId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateIsNull() {
            addCriterion("after_sale_date is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateIsNotNull() {
            addCriterion("after_sale_date is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateEqualTo(String value) {
            addCriterion("after_sale_date =", value, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateNotEqualTo(String value) {
            addCriterion("after_sale_date <>", value, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateGreaterThan(String value) {
            addCriterion("after_sale_date >", value, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale_date >=", value, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateLessThan(String value) {
            addCriterion("after_sale_date <", value, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateLessThanOrEqualTo(String value) {
            addCriterion("after_sale_date <=", value, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateLike(String value) {
            addCriterion("after_sale_date like", value, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateNotLike(String value) {
            addCriterion("after_sale_date not like", value, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateIn(List<String> values) {
            addCriterion("after_sale_date in", values, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateNotIn(List<String> values) {
            addCriterion("after_sale_date not in", values, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateBetween(String value1, String value2) {
            addCriterion("after_sale_date between", value1, value2, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleDateNotBetween(String value1, String value2) {
            addCriterion("after_sale_date not between", value1, value2, "afterSaleDate");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneIsNull() {
            addCriterion("after_sale_client_phone is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneIsNotNull() {
            addCriterion("after_sale_client_phone is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneEqualTo(String value) {
            addCriterion("after_sale_client_phone =", value, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneNotEqualTo(String value) {
            addCriterion("after_sale_client_phone <>", value, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneGreaterThan(String value) {
            addCriterion("after_sale_client_phone >", value, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale_client_phone >=", value, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneLessThan(String value) {
            addCriterion("after_sale_client_phone <", value, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneLessThanOrEqualTo(String value) {
            addCriterion("after_sale_client_phone <=", value, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneLike(String value) {
            addCriterion("after_sale_client_phone like", value, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneNotLike(String value) {
            addCriterion("after_sale_client_phone not like", value, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneIn(List<String> values) {
            addCriterion("after_sale_client_phone in", values, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneNotIn(List<String> values) {
            addCriterion("after_sale_client_phone not in", values, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneBetween(String value1, String value2) {
            addCriterion("after_sale_client_phone between", value1, value2, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientPhoneNotBetween(String value1, String value2) {
            addCriterion("after_sale_client_phone not between", value1, value2, "afterSaleClientPhone");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdIsNull() {
            addCriterion("after_sale_client_id is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdIsNotNull() {
            addCriterion("after_sale_client_id is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdEqualTo(String value) {
            addCriterion("after_sale_client_id =", value, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdNotEqualTo(String value) {
            addCriterion("after_sale_client_id <>", value, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdGreaterThan(String value) {
            addCriterion("after_sale_client_id >", value, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale_client_id >=", value, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdLessThan(String value) {
            addCriterion("after_sale_client_id <", value, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdLessThanOrEqualTo(String value) {
            addCriterion("after_sale_client_id <=", value, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdLike(String value) {
            addCriterion("after_sale_client_id like", value, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdNotLike(String value) {
            addCriterion("after_sale_client_id not like", value, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdIn(List<String> values) {
            addCriterion("after_sale_client_id in", values, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdNotIn(List<String> values) {
            addCriterion("after_sale_client_id not in", values, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdBetween(String value1, String value2) {
            addCriterion("after_sale_client_id between", value1, value2, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleClientIdNotBetween(String value1, String value2) {
            addCriterion("after_sale_client_id not between", value1, value2, "afterSaleClientId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageIsNull() {
            addCriterion("after_sale_message is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageIsNotNull() {
            addCriterion("after_sale_message is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageEqualTo(String value) {
            addCriterion("after_sale_message =", value, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageNotEqualTo(String value) {
            addCriterion("after_sale_message <>", value, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageGreaterThan(String value) {
            addCriterion("after_sale_message >", value, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale_message >=", value, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageLessThan(String value) {
            addCriterion("after_sale_message <", value, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageLessThanOrEqualTo(String value) {
            addCriterion("after_sale_message <=", value, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageLike(String value) {
            addCriterion("after_sale_message like", value, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageNotLike(String value) {
            addCriterion("after_sale_message not like", value, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageIn(List<String> values) {
            addCriterion("after_sale_message in", values, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageNotIn(List<String> values) {
            addCriterion("after_sale_message not in", values, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageBetween(String value1, String value2) {
            addCriterion("after_sale_message between", value1, value2, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleMessageNotBetween(String value1, String value2) {
            addCriterion("after_sale_message not between", value1, value2, "afterSaleMessage");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdIsNull() {
            addCriterion("after_sale_employee_id is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdIsNotNull() {
            addCriterion("after_sale_employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdEqualTo(String value) {
            addCriterion("after_sale_employee_id =", value, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdNotEqualTo(String value) {
            addCriterion("after_sale_employee_id <>", value, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdGreaterThan(String value) {
            addCriterion("after_sale_employee_id >", value, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale_employee_id >=", value, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdLessThan(String value) {
            addCriterion("after_sale_employee_id <", value, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdLessThanOrEqualTo(String value) {
            addCriterion("after_sale_employee_id <=", value, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdLike(String value) {
            addCriterion("after_sale_employee_id like", value, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdNotLike(String value) {
            addCriterion("after_sale_employee_id not like", value, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdIn(List<String> values) {
            addCriterion("after_sale_employee_id in", values, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdNotIn(List<String> values) {
            addCriterion("after_sale_employee_id not in", values, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdBetween(String value1, String value2) {
            addCriterion("after_sale_employee_id between", value1, value2, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEmployeeIdNotBetween(String value1, String value2) {
            addCriterion("after_sale_employee_id not between", value1, value2, "afterSaleEmployeeId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateIsNull() {
            addCriterion("after_sale_state is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateIsNotNull() {
            addCriterion("after_sale_state is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateEqualTo(String value) {
            addCriterion("after_sale_state =", value, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateNotEqualTo(String value) {
            addCriterion("after_sale_state <>", value, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateGreaterThan(String value) {
            addCriterion("after_sale_state >", value, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale_state >=", value, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateLessThan(String value) {
            addCriterion("after_sale_state <", value, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateLessThanOrEqualTo(String value) {
            addCriterion("after_sale_state <=", value, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateLike(String value) {
            addCriterion("after_sale_state like", value, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateNotLike(String value) {
            addCriterion("after_sale_state not like", value, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateIn(List<String> values) {
            addCriterion("after_sale_state in", values, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateNotIn(List<String> values) {
            addCriterion("after_sale_state not in", values, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateBetween(String value1, String value2) {
            addCriterion("after_sale_state between", value1, value2, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleStateNotBetween(String value1, String value2) {
            addCriterion("after_sale_state not between", value1, value2, "afterSaleState");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdIsNull() {
            addCriterion("after_sale_car_id is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdIsNotNull() {
            addCriterion("after_sale_car_id is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdEqualTo(String value) {
            addCriterion("after_sale_car_id =", value, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdNotEqualTo(String value) {
            addCriterion("after_sale_car_id <>", value, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdGreaterThan(String value) {
            addCriterion("after_sale_car_id >", value, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale_car_id >=", value, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdLessThan(String value) {
            addCriterion("after_sale_car_id <", value, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdLessThanOrEqualTo(String value) {
            addCriterion("after_sale_car_id <=", value, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdLike(String value) {
            addCriterion("after_sale_car_id like", value, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdNotLike(String value) {
            addCriterion("after_sale_car_id not like", value, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdIn(List<String> values) {
            addCriterion("after_sale_car_id in", values, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdNotIn(List<String> values) {
            addCriterion("after_sale_car_id not in", values, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdBetween(String value1, String value2) {
            addCriterion("after_sale_car_id between", value1, value2, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleCarIdNotBetween(String value1, String value2) {
            addCriterion("after_sale_car_id not between", value1, value2, "afterSaleCarId");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidIsNull() {
            addCriterion("after_sale_eid is null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidIsNotNull() {
            addCriterion("after_sale_eid is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidEqualTo(String value) {
            addCriterion("after_sale_eid =", value, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidNotEqualTo(String value) {
            addCriterion("after_sale_eid <>", value, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidGreaterThan(String value) {
            addCriterion("after_sale_eid >", value, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale_eid >=", value, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidLessThan(String value) {
            addCriterion("after_sale_eid <", value, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidLessThanOrEqualTo(String value) {
            addCriterion("after_sale_eid <=", value, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidLike(String value) {
            addCriterion("after_sale_eid like", value, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidNotLike(String value) {
            addCriterion("after_sale_eid not like", value, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidIn(List<String> values) {
            addCriterion("after_sale_eid in", values, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidNotIn(List<String> values) {
            addCriterion("after_sale_eid not in", values, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidBetween(String value1, String value2) {
            addCriterion("after_sale_eid between", value1, value2, "afterSaleEid");
            return (Criteria) this;
        }

        public Criteria andAfterSaleEidNotBetween(String value1, String value2) {
            addCriterion("after_sale_eid not between", value1, value2, "afterSaleEid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table after_sale
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 11 23:23:02 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table after_sale
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}