package com.zhang.automobile_management_system.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class AfterSale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private Integer afterSaleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_date
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String afterSaleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_client_phone
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String afterSaleClientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_client_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String afterSaleClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_message
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String afterSaleMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_employee_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String afterSaleEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_state
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String afterSaleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_car_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String afterSaleCarId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_sale.after_sale_eid
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String afterSaleEid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_id
     *
     * @return the value of after_sale.after_sale_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public Integer getAfterSaleId() {
        return afterSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_id
     *
     * @param afterSaleId the value for after_sale.after_sale_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleId(Integer afterSaleId) {
        this.afterSaleId = afterSaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_date
     *
     * @return the value of after_sale.after_sale_date
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getAfterSaleDate() {
        return afterSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_date
     *
     * @param afterSaleDate the value for after_sale.after_sale_date
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleDate(String afterSaleDate) {
        this.afterSaleDate = afterSaleDate == null ? null : afterSaleDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_client_phone
     *
     * @return the value of after_sale.after_sale_client_phone
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getAfterSaleClientPhone() {
        return afterSaleClientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_client_phone
     *
     * @param afterSaleClientPhone the value for after_sale.after_sale_client_phone
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleClientPhone(String afterSaleClientPhone) {
        this.afterSaleClientPhone = afterSaleClientPhone == null ? null : afterSaleClientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_client_id
     *
     * @return the value of after_sale.after_sale_client_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getAfterSaleClientId() {
        return afterSaleClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_client_id
     *
     * @param afterSaleClientId the value for after_sale.after_sale_client_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleClientId(String afterSaleClientId) {
        this.afterSaleClientId = afterSaleClientId == null ? null : afterSaleClientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_message
     *
     * @return the value of after_sale.after_sale_message
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getAfterSaleMessage() {
        return afterSaleMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_message
     *
     * @param afterSaleMessage the value for after_sale.after_sale_message
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleMessage(String afterSaleMessage) {
        this.afterSaleMessage = afterSaleMessage == null ? null : afterSaleMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_employee_id
     *
     * @return the value of after_sale.after_sale_employee_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getAfterSaleEmployeeId() {
        return afterSaleEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_employee_id
     *
     * @param afterSaleEmployeeId the value for after_sale.after_sale_employee_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleEmployeeId(String afterSaleEmployeeId) {
        this.afterSaleEmployeeId = afterSaleEmployeeId == null ? null : afterSaleEmployeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_state
     *
     * @return the value of after_sale.after_sale_state
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getAfterSaleState() {
        return afterSaleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_state
     *
     * @param afterSaleState the value for after_sale.after_sale_state
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleState(String afterSaleState) {
        this.afterSaleState = afterSaleState == null ? null : afterSaleState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_car_id
     *
     * @return the value of after_sale.after_sale_car_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getAfterSaleCarId() {
        return afterSaleCarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_car_id
     *
     * @param afterSaleCarId the value for after_sale.after_sale_car_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleCarId(String afterSaleCarId) {
        this.afterSaleCarId = afterSaleCarId == null ? null : afterSaleCarId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_sale.after_sale_eid
     *
     * @return the value of after_sale.after_sale_eid
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getAfterSaleEid() {
        return afterSaleEid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_sale.after_sale_eid
     *
     * @param afterSaleEid the value for after_sale.after_sale_eid
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setAfterSaleEid(String afterSaleEid) {
        this.afterSaleEid = afterSaleEid == null ? null : afterSaleEid.trim();
    }
}