package com.zhang.automobile_management_system.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.stereotype.Component;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Component
public class Announcement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcement_id
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    private Integer announcementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcement_message
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    private String announcementMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcement_id
     *
     * @return the value of announcement.announcement_id
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    public Integer getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcement_id
     *
     * @param announcementId the value for announcement.announcement_id
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcement_message
     *
     * @return the value of announcement.announcement_message
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    public String getAnnouncementMessage() {
        return announcementMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcement_message
     *
     * @param announcementMessage the value for announcement.announcement_message
     *
     * @mbggenerated Sun Apr 16 21:00:59 CST 2023
     */
    public void setAnnouncementMessage(String announcementMessage) {
        this.announcementMessage = announcementMessage == null ? null : announcementMessage.trim();
    }
}