package com.zhang.automobile_management_system.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Data
@Component
public class CarMessagesSale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_stock_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carStockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_brand
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_version
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private BigDecimal carVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_type
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_displacement
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private BigDecimal carDisplacement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_gearbox
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carGearbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_color
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_price
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private BigDecimal carPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_energy
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carEnergy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_sale_employee
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carSaleEmployee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_messages_sale.car_provide
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carProvide;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_id
     *
     * @return the value of car_messages_sale.car_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_id
     *
     * @param carId the value for car_messages_sale.car_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_stock_id
     *
     * @return the value of car_messages_sale.car_stock_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarStockId() {
        return carStockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_stock_id
     *
     * @param carStockId the value for car_messages_sale.car_stock_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarStockId(String carStockId) {
        this.carStockId = carStockId == null ? null : carStockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_name
     *
     * @return the value of car_messages_sale.car_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarName() {
        return carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_name
     *
     * @param carName the value for car_messages_sale.car_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarName(String carName) {
        this.carName = carName == null ? null : carName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_brand
     *
     * @return the value of car_messages_sale.car_brand
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarBrand() {
        return carBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_brand
     *
     * @param carBrand the value for car_messages_sale.car_brand
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand == null ? null : carBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_version
     *
     * @return the value of car_messages_sale.car_version
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public BigDecimal getCarVersion() {
        return carVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_version
     *
     * @param carVersion the value for car_messages_sale.car_version
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarVersion(BigDecimal carVersion) {
        this.carVersion = carVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_type
     *
     * @return the value of car_messages_sale.car_type
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_type
     *
     * @param carType the value for car_messages_sale.car_type
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_displacement
     *
     * @return the value of car_messages_sale.car_displacement
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public BigDecimal getCarDisplacement() {
        return carDisplacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_displacement
     *
     * @param carDisplacement the value for car_messages_sale.car_displacement
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarDisplacement(BigDecimal carDisplacement) {
        this.carDisplacement = carDisplacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_gearbox
     *
     * @return the value of car_messages_sale.car_gearbox
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarGearbox() {
        return carGearbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_gearbox
     *
     * @param carGearbox the value for car_messages_sale.car_gearbox
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarGearbox(String carGearbox) {
        this.carGearbox = carGearbox == null ? null : carGearbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_color
     *
     * @return the value of car_messages_sale.car_color
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarColor() {
        return carColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_color
     *
     * @param carColor the value for car_messages_sale.car_color
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarColor(String carColor) {
        this.carColor = carColor == null ? null : carColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_price
     *
     * @return the value of car_messages_sale.car_price
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public BigDecimal getCarPrice() {
        return carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_price
     *
     * @param carPrice the value for car_messages_sale.car_price
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarPrice(BigDecimal carPrice) {
        this.carPrice = carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_energy
     *
     * @return the value of car_messages_sale.car_energy
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarEnergy() {
        return carEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_energy
     *
     * @param carEnergy the value for car_messages_sale.car_energy
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarEnergy(String carEnergy) {
        this.carEnergy = carEnergy == null ? null : carEnergy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_sale_employee
     *
     * @return the value of car_messages_sale.car_sale_employee
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarSaleEmployee() {
        return carSaleEmployee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_sale_employee
     *
     * @param carSaleEmployee the value for car_messages_sale.car_sale_employee
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarSaleEmployee(String carSaleEmployee) {
        this.carSaleEmployee = carSaleEmployee == null ? null : carSaleEmployee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_messages_sale.car_provide
     *
     * @return the value of car_messages_sale.car_provide
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarProvide() {
        return carProvide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_messages_sale.car_provide
     *
     * @param carProvide the value for car_messages_sale.car_provide
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarProvide(String carProvide) {
        this.carProvide = carProvide == null ? null : carProvide.trim();
    }
}