package com.zhang.automobile_management_system.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@AllArgsConstructor@NoArgsConstructor
@ToString
public class CarOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_order.order_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_order.order_employee_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    private String orderEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_order.order_date
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    private String orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_order.order_car_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    private String orderCarId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_order.order_client_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    private String orderClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_order.order_state
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    private String orderState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_order.order_id
     *
     * @return the value of car_order.order_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_order.order_id
     *
     * @param orderId the value for car_order.order_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_order.order_employee_id
     *
     * @return the value of car_order.order_employee_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public String getOrderEmployeeId() {
        return orderEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_order.order_employee_id
     *
     * @param orderEmployeeId the value for car_order.order_employee_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void setOrderEmployeeId(String orderEmployeeId) {
        this.orderEmployeeId = orderEmployeeId == null ? null : orderEmployeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_order.order_date
     *
     * @return the value of car_order.order_date
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_order.order_date
     *
     * @param orderDate the value for car_order.order_date
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate == null ? null : orderDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_order.order_car_id
     *
     * @return the value of car_order.order_car_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public String getOrderCarId() {
        return orderCarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_order.order_car_id
     *
     * @param orderCarId the value for car_order.order_car_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void setOrderCarId(String orderCarId) {
        this.orderCarId = orderCarId == null ? null : orderCarId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_order.order_client_id
     *
     * @return the value of car_order.order_client_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public String getOrderClientId() {
        return orderClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_order.order_client_id
     *
     * @param orderClientId the value for car_order.order_client_id
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void setOrderClientId(String orderClientId) {
        this.orderClientId = orderClientId == null ? null : orderClientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_order.order_state
     *
     * @return the value of car_order.order_state
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_order.order_state
     *
     * @param orderState the value for car_order.order_state
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }
}