package com.zhang.automobile_management_system.bean;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
@Component
public class CarOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public CarOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdIsNull() {
            addCriterion("order_employee_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdIsNotNull() {
            addCriterion("order_employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdEqualTo(String value) {
            addCriterion("order_employee_id =", value, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdNotEqualTo(String value) {
            addCriterion("order_employee_id <>", value, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdGreaterThan(String value) {
            addCriterion("order_employee_id >", value, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_employee_id >=", value, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdLessThan(String value) {
            addCriterion("order_employee_id <", value, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdLessThanOrEqualTo(String value) {
            addCriterion("order_employee_id <=", value, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdLike(String value) {
            addCriterion("order_employee_id like", value, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdNotLike(String value) {
            addCriterion("order_employee_id not like", value, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdIn(List<String> values) {
            addCriterion("order_employee_id in", values, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdNotIn(List<String> values) {
            addCriterion("order_employee_id not in", values, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdBetween(String value1, String value2) {
            addCriterion("order_employee_id between", value1, value2, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderEmployeeIdNotBetween(String value1, String value2) {
            addCriterion("order_employee_id not between", value1, value2, "orderEmployeeId");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNull() {
            addCriterion("order_date is null");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNotNull() {
            addCriterion("order_date is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDateEqualTo(String value) {
            addCriterion("order_date =", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotEqualTo(String value) {
            addCriterion("order_date <>", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThan(String value) {
            addCriterion("order_date >", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThanOrEqualTo(String value) {
            addCriterion("order_date >=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThan(String value) {
            addCriterion("order_date <", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThanOrEqualTo(String value) {
            addCriterion("order_date <=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLike(String value) {
            addCriterion("order_date like", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotLike(String value) {
            addCriterion("order_date not like", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateIn(List<String> values) {
            addCriterion("order_date in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotIn(List<String> values) {
            addCriterion("order_date not in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateBetween(String value1, String value2) {
            addCriterion("order_date between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotBetween(String value1, String value2) {
            addCriterion("order_date not between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdIsNull() {
            addCriterion("order_car_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdIsNotNull() {
            addCriterion("order_car_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdEqualTo(String value) {
            addCriterion("order_car_id =", value, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdNotEqualTo(String value) {
            addCriterion("order_car_id <>", value, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdGreaterThan(String value) {
            addCriterion("order_car_id >", value, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_car_id >=", value, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdLessThan(String value) {
            addCriterion("order_car_id <", value, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdLessThanOrEqualTo(String value) {
            addCriterion("order_car_id <=", value, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdLike(String value) {
            addCriterion("order_car_id like", value, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdNotLike(String value) {
            addCriterion("order_car_id not like", value, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdIn(List<String> values) {
            addCriterion("order_car_id in", values, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdNotIn(List<String> values) {
            addCriterion("order_car_id not in", values, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdBetween(String value1, String value2) {
            addCriterion("order_car_id between", value1, value2, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderCarIdNotBetween(String value1, String value2) {
            addCriterion("order_car_id not between", value1, value2, "orderCarId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdIsNull() {
            addCriterion("order_client_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdIsNotNull() {
            addCriterion("order_client_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdEqualTo(String value) {
            addCriterion("order_client_id =", value, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdNotEqualTo(String value) {
            addCriterion("order_client_id <>", value, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdGreaterThan(String value) {
            addCriterion("order_client_id >", value, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_client_id >=", value, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdLessThan(String value) {
            addCriterion("order_client_id <", value, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdLessThanOrEqualTo(String value) {
            addCriterion("order_client_id <=", value, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdLike(String value) {
            addCriterion("order_client_id like", value, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdNotLike(String value) {
            addCriterion("order_client_id not like", value, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdIn(List<String> values) {
            addCriterion("order_client_id in", values, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdNotIn(List<String> values) {
            addCriterion("order_client_id not in", values, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdBetween(String value1, String value2) {
            addCriterion("order_client_id between", value1, value2, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderClientIdNotBetween(String value1, String value2) {
            addCriterion("order_client_id not between", value1, value2, "orderClientId");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNull() {
            addCriterion("order_state is null");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNotNull() {
            addCriterion("order_state is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStateEqualTo(String value) {
            addCriterion("order_state =", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotEqualTo(String value) {
            addCriterion("order_state <>", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThan(String value) {
            addCriterion("order_state >", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThanOrEqualTo(String value) {
            addCriterion("order_state >=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThan(String value) {
            addCriterion("order_state <", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThanOrEqualTo(String value) {
            addCriterion("order_state <=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLike(String value) {
            addCriterion("order_state like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotLike(String value) {
            addCriterion("order_state not like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateIn(List<String> values) {
            addCriterion("order_state in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotIn(List<String> values) {
            addCriterion("order_state not in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateBetween(String value1, String value2) {
            addCriterion("order_state between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotBetween(String value1, String value2) {
            addCriterion("order_state not between", value1, value2, "orderState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_order
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 12 16:40:47 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table car_order
     *
     * @mbggenerated Wed Apr 12 16:40:47 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}