package com.zhang.automobile_management_system.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Client {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_name
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_phone
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String clientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.client_sex
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    private String clientSex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_id
     *
     * @return the value of client.client_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_id
     *
     * @param clientId the value for client.client_id
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_name
     *
     * @return the value of client.client_name
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_name
     *
     * @param clientName the value for client.client_name
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_phone
     *
     * @return the value of client.client_phone
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getClientPhone() {
        return clientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_phone
     *
     * @param clientPhone the value for client.client_phone
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setClientPhone(String clientPhone) {
        this.clientPhone = clientPhone == null ? null : clientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.client_sex
     *
     * @return the value of client.client_sex
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public String getClientSex() {
        return clientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.client_sex
     *
     * @param clientSex the value for client.client_sex
     *
     * @mbggenerated Tue Apr 11 23:23:02 CST 2023
     */
    public void setClientSex(String clientSex) {
        this.clientSex = clientSex == null ? null : clientSex.trim();
    }
}