package com.zhang.automobile_management_system.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Component
public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_id
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_name
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_phone
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_sex
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeeSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_role
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeeRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_salary
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private BigDecimal employeeSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_username
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeeUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_password
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_permission
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeePermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_date
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    private String employeeDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_id
     *
     * @return the value of employee.employee_id
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_id
     *
     * @param employeeId the value for employee.employee_id
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_name
     *
     * @return the value of employee.employee_name
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_name
     *
     * @param employeeName the value for employee.employee_name
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_phone
     *
     * @return the value of employee.employee_phone
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeePhone() {
        return employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_phone
     *
     * @param employeePhone the value for employee.employee_phone
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeePhone(String employeePhone) {
        this.employeePhone = employeePhone == null ? null : employeePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_sex
     *
     * @return the value of employee.employee_sex
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeeSex() {
        return employeeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_sex
     *
     * @param employeeSex the value for employee.employee_sex
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeeSex(String employeeSex) {
        this.employeeSex = employeeSex == null ? null : employeeSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_role
     *
     * @return the value of employee.employee_role
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeeRole() {
        return employeeRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_role
     *
     * @param employeeRole the value for employee.employee_role
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeeRole(String employeeRole) {
        this.employeeRole = employeeRole == null ? null : employeeRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_salary
     *
     * @return the value of employee.employee_salary
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public BigDecimal getEmployeeSalary() {
        return employeeSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_salary
     *
     * @param employeeSalary the value for employee.employee_salary
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeeSalary(BigDecimal employeeSalary) {
        this.employeeSalary = employeeSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_username
     *
     * @return the value of employee.employee_username
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeeUsername() {
        return employeeUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_username
     *
     * @param employeeUsername the value for employee.employee_username
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeeUsername(String employeeUsername) {
        this.employeeUsername = employeeUsername == null ? null : employeeUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_password
     *
     * @return the value of employee.employee_password
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeePassword() {
        return employeePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_password
     *
     * @param employeePassword the value for employee.employee_password
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeePassword(String employeePassword) {
        this.employeePassword = employeePassword == null ? null : employeePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_permission
     *
     * @return the value of employee.employee_permission
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeePermission() {
        return employeePermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_permission
     *
     * @param employeePermission the value for employee.employee_permission
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeePermission(String employeePermission) {
        this.employeePermission = employeePermission == null ? null : employeePermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_date
     *
     * @return the value of employee.employee_date
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public String getEmployeeDate() {
        return employeeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_date
     *
     * @param employeeDate the value for employee.employee_date
     *
     * @mbggenerated Sun Apr 23 19:58:50 CST 2023
     */
    public void setEmployeeDate(String employeeDate) {
        this.employeeDate = employeeDate == null ? null : employeeDate.trim();
    }
}