package com.zhang.automobile_management_system.bean;

import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
@Component
public class InventoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public InventoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInventoryIdIsNull() {
            addCriterion("inventory_id is null");
            return (Criteria) this;
        }

        public Criteria andInventoryIdIsNotNull() {
            addCriterion("inventory_id is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryIdEqualTo(Integer value) {
            addCriterion("inventory_id =", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdNotEqualTo(Integer value) {
            addCriterion("inventory_id <>", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdGreaterThan(Integer value) {
            addCriterion("inventory_id >", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("inventory_id >=", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdLessThan(Integer value) {
            addCriterion("inventory_id <", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("inventory_id <=", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdIn(List<Integer> values) {
            addCriterion("inventory_id in", values, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdNotIn(List<Integer> values) {
            addCriterion("inventory_id not in", values, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdBetween(Integer value1, Integer value2) {
            addCriterion("inventory_id between", value1, value2, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("inventory_id not between", value1, value2, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryNameIsNull() {
            addCriterion("inventory_name is null");
            return (Criteria) this;
        }

        public Criteria andInventoryNameIsNotNull() {
            addCriterion("inventory_name is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryNameEqualTo(String value) {
            addCriterion("inventory_name =", value, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameNotEqualTo(String value) {
            addCriterion("inventory_name <>", value, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameGreaterThan(String value) {
            addCriterion("inventory_name >", value, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("inventory_name >=", value, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameLessThan(String value) {
            addCriterion("inventory_name <", value, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameLessThanOrEqualTo(String value) {
            addCriterion("inventory_name <=", value, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameLike(String value) {
            addCriterion("inventory_name like", value, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameNotLike(String value) {
            addCriterion("inventory_name not like", value, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameIn(List<String> values) {
            addCriterion("inventory_name in", values, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameNotIn(List<String> values) {
            addCriterion("inventory_name not in", values, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameBetween(String value1, String value2) {
            addCriterion("inventory_name between", value1, value2, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryNameNotBetween(String value1, String value2) {
            addCriterion("inventory_name not between", value1, value2, "inventoryName");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandIsNull() {
            addCriterion("inventory_brand is null");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandIsNotNull() {
            addCriterion("inventory_brand is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandEqualTo(String value) {
            addCriterion("inventory_brand =", value, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandNotEqualTo(String value) {
            addCriterion("inventory_brand <>", value, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandGreaterThan(String value) {
            addCriterion("inventory_brand >", value, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandGreaterThanOrEqualTo(String value) {
            addCriterion("inventory_brand >=", value, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandLessThan(String value) {
            addCriterion("inventory_brand <", value, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandLessThanOrEqualTo(String value) {
            addCriterion("inventory_brand <=", value, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandLike(String value) {
            addCriterion("inventory_brand like", value, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandNotLike(String value) {
            addCriterion("inventory_brand not like", value, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandIn(List<String> values) {
            addCriterion("inventory_brand in", values, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandNotIn(List<String> values) {
            addCriterion("inventory_brand not in", values, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandBetween(String value1, String value2) {
            addCriterion("inventory_brand between", value1, value2, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryBrandNotBetween(String value1, String value2) {
            addCriterion("inventory_brand not between", value1, value2, "inventoryBrand");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameIsNull() {
            addCriterion("inventory_car_name is null");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameIsNotNull() {
            addCriterion("inventory_car_name is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameEqualTo(String value) {
            addCriterion("inventory_car_name =", value, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameNotEqualTo(String value) {
            addCriterion("inventory_car_name <>", value, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameGreaterThan(String value) {
            addCriterion("inventory_car_name >", value, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameGreaterThanOrEqualTo(String value) {
            addCriterion("inventory_car_name >=", value, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameLessThan(String value) {
            addCriterion("inventory_car_name <", value, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameLessThanOrEqualTo(String value) {
            addCriterion("inventory_car_name <=", value, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameLike(String value) {
            addCriterion("inventory_car_name like", value, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameNotLike(String value) {
            addCriterion("inventory_car_name not like", value, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameIn(List<String> values) {
            addCriterion("inventory_car_name in", values, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameNotIn(List<String> values) {
            addCriterion("inventory_car_name not in", values, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameBetween(String value1, String value2) {
            addCriterion("inventory_car_name between", value1, value2, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryCarNameNotBetween(String value1, String value2) {
            addCriterion("inventory_car_name not between", value1, value2, "inventoryCarName");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeIsNull() {
            addCriterion("inventory_type is null");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeIsNotNull() {
            addCriterion("inventory_type is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeEqualTo(String value) {
            addCriterion("inventory_type =", value, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeNotEqualTo(String value) {
            addCriterion("inventory_type <>", value, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeGreaterThan(String value) {
            addCriterion("inventory_type >", value, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeGreaterThanOrEqualTo(String value) {
            addCriterion("inventory_type >=", value, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeLessThan(String value) {
            addCriterion("inventory_type <", value, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeLessThanOrEqualTo(String value) {
            addCriterion("inventory_type <=", value, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeLike(String value) {
            addCriterion("inventory_type like", value, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeNotLike(String value) {
            addCriterion("inventory_type not like", value, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeIn(List<String> values) {
            addCriterion("inventory_type in", values, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeNotIn(List<String> values) {
            addCriterion("inventory_type not in", values, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeBetween(String value1, String value2) {
            addCriterion("inventory_type between", value1, value2, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryTypeNotBetween(String value1, String value2) {
            addCriterion("inventory_type not between", value1, value2, "inventoryType");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionIsNull() {
            addCriterion("inventory_version is null");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionIsNotNull() {
            addCriterion("inventory_version is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionEqualTo(BigDecimal value) {
            addCriterion("inventory_version =", value, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionNotEqualTo(BigDecimal value) {
            addCriterion("inventory_version <>", value, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionGreaterThan(BigDecimal value) {
            addCriterion("inventory_version >", value, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("inventory_version >=", value, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionLessThan(BigDecimal value) {
            addCriterion("inventory_version <", value, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("inventory_version <=", value, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionIn(List<BigDecimal> values) {
            addCriterion("inventory_version in", values, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionNotIn(List<BigDecimal> values) {
            addCriterion("inventory_version not in", values, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inventory_version between", value1, value2, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryVersionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("inventory_version not between", value1, value2, "inventoryVersion");
            return (Criteria) this;
        }

        public Criteria andInventoryCountIsNull() {
            addCriterion("inventory_count is null");
            return (Criteria) this;
        }

        public Criteria andInventoryCountIsNotNull() {
            addCriterion("inventory_count is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryCountEqualTo(Integer value) {
            addCriterion("inventory_count =", value, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountNotEqualTo(Integer value) {
            addCriterion("inventory_count <>", value, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountGreaterThan(Integer value) {
            addCriterion("inventory_count >", value, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("inventory_count >=", value, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountLessThan(Integer value) {
            addCriterion("inventory_count <", value, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountLessThanOrEqualTo(Integer value) {
            addCriterion("inventory_count <=", value, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountIn(List<Integer> values) {
            addCriterion("inventory_count in", values, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountNotIn(List<Integer> values) {
            addCriterion("inventory_count not in", values, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountBetween(Integer value1, Integer value2) {
            addCriterion("inventory_count between", value1, value2, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andInventoryCountNotBetween(Integer value1, Integer value2) {
            addCriterion("inventory_count not between", value1, value2, "inventoryCount");
            return (Criteria) this;
        }

        public Criteria andCarProvideIsNull() {
            addCriterion("car_provide is null");
            return (Criteria) this;
        }

        public Criteria andCarProvideIsNotNull() {
            addCriterion("car_provide is not null");
            return (Criteria) this;
        }

        public Criteria andCarProvideEqualTo(String value) {
            addCriterion("car_provide =", value, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideNotEqualTo(String value) {
            addCriterion("car_provide <>", value, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideGreaterThan(String value) {
            addCriterion("car_provide >", value, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideGreaterThanOrEqualTo(String value) {
            addCriterion("car_provide >=", value, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideLessThan(String value) {
            addCriterion("car_provide <", value, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideLessThanOrEqualTo(String value) {
            addCriterion("car_provide <=", value, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideLike(String value) {
            addCriterion("car_provide like", value, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideNotLike(String value) {
            addCriterion("car_provide not like", value, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideIn(List<String> values) {
            addCriterion("car_provide in", values, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideNotIn(List<String> values) {
            addCriterion("car_provide not in", values, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideBetween(String value1, String value2) {
            addCriterion("car_provide between", value1, value2, "carProvide");
            return (Criteria) this;
        }

        public Criteria andCarProvideNotBetween(String value1, String value2) {
            addCriterion("car_provide not between", value1, value2, "carProvide");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inventory
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 20 13:40:16 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inventory
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}