package com.zhang.automobile_management_system.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
@Data
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Component
public class Inventory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private Integer inventoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String inventoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_brand
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String inventoryBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_car_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String inventoryCarName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_type
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String inventoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_version
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private BigDecimal inventoryVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_count
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private Integer inventoryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.car_provide
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    private String carProvide;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_id
     *
     * @return the value of inventory.inventory_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public Integer getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_id
     *
     * @param inventoryId the value for inventory.inventory_id
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_name
     *
     * @return the value of inventory.inventory_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getInventoryName() {
        return inventoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_name
     *
     * @param inventoryName the value for inventory.inventory_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setInventoryName(String inventoryName) {
        this.inventoryName = inventoryName == null ? null : inventoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_brand
     *
     * @return the value of inventory.inventory_brand
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getInventoryBrand() {
        return inventoryBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_brand
     *
     * @param inventoryBrand the value for inventory.inventory_brand
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setInventoryBrand(String inventoryBrand) {
        this.inventoryBrand = inventoryBrand == null ? null : inventoryBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_car_name
     *
     * @return the value of inventory.inventory_car_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getInventoryCarName() {
        return inventoryCarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_car_name
     *
     * @param inventoryCarName the value for inventory.inventory_car_name
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setInventoryCarName(String inventoryCarName) {
        this.inventoryCarName = inventoryCarName == null ? null : inventoryCarName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_type
     *
     * @return the value of inventory.inventory_type
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getInventoryType() {
        return inventoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_type
     *
     * @param inventoryType the value for inventory.inventory_type
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setInventoryType(String inventoryType) {
        this.inventoryType = inventoryType == null ? null : inventoryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_version
     *
     * @return the value of inventory.inventory_version
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public BigDecimal getInventoryVersion() {
        return inventoryVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_version
     *
     * @param inventoryVersion the value for inventory.inventory_version
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setInventoryVersion(BigDecimal inventoryVersion) {
        this.inventoryVersion = inventoryVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_count
     *
     * @return the value of inventory.inventory_count
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public Integer getInventoryCount() {
        return inventoryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_count
     *
     * @param inventoryCount the value for inventory.inventory_count
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setInventoryCount(Integer inventoryCount) {
        this.inventoryCount = inventoryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.car_provide
     *
     * @return the value of inventory.car_provide
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public String getCarProvide() {
        return carProvide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.car_provide
     *
     * @param carProvide the value for inventory.car_provide
     *
     * @mbggenerated Thu Apr 20 13:40:16 CST 2023
     */
    public void setCarProvide(String carProvide) {
        this.carProvide = carProvide == null ? null : carProvide.trim();
    }
}